name: Manual Firefox for Android Build

on:
  workflow_dispatch:  # Запуск вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Rust (required by mach)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Python 3 and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-venv python3-pip
          python3 -m venv venv
          source venv/bin/activate
          pip install -r python/requirements.txt

      - name: Bootstrap Firefox build environment
        run: ./mach bootstrap --no-interactive

      - name: Build using mach
        run: ./mach build

      - name: Package APK
        run: ./mach package

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: fennec-apk
          path: obj-arm64-v8a/dist/*.apk
